### ISSUE TITLE
How to call and use result-analyzer.js

### ISSUE THREAD

**Issue by dingodoppelt** [dtinth/jitter-analysis#1]
Hi!
First off I want to thank you for all your great work concerning jamulus :)
I'm currently having issues with my ISP so I wanted to gather some data for them to work with and your script seems perfect for that!
Anyhow, I can't get the result-analyzer to output anything but this:
```
### Root-mean-sequared of delays above mean ping + 3ms (ms, lower is better) ###
RMS     server1 server2
server1 NaN     NaN
server2 NaN     NaN

### Number of packets above mean ping + 3ms (lower is better) ###
Jitter  server1 server2
server1 0       0
server2 0       0

### Numbers of packets lost (no repsonse in 1000ms, lower is better) ###
Lost    server1 server2
server1 0       0
server2 0       0

### Number of packets received (higher is better) ###
Received        server1 server2
server1 0       0
server2 0       0

### Average ping value (ms, lower is better) ###
Mean Ping       server1 server2
server1 NaN     NaN
server2 NaN     NaN
```

Could you give me a hint at what the proper way to call this script would be?
The pinger itself is working great and seems to be spitting out interesting and useful data so I'd really like to be able to get the result-analyzer to display it so I have something to send to my ISP.
Keep up the great work!
cheers, nils

**Comment by dtinth** [comment]
@dingodoppelt You will have to put the result files in `plays/private/results/*.log`, named after each server. Then hopefully the script should pick it up. Please let me know if that works for you…

**Comment by dingodoppelt** [comment]
Yep, that works!
Thanks a lot :)
